controller_frequency: 3.0
planner_frequency: 1.0

TrajectoryPlannerROS:
  max_vel_x: 0.3 #0.5
  min_vel_x: 0.01 #0.01

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot


  max_vel_theta: 1.0 #1.5
  max_rotational_vel: 0.5
  escape_vel: -0.3
  min_in_place_rotational_vel: 0.4

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  sim_time: 1.0

  vx_samples: 5.0
  vy_samples: 1   
  vtheta_samples: 10.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.05 #que tanto debe de esquivar obstaculso
  meter_scoring: true


  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom

  holonomic_robot: false
